config/routes.rb
DdeServer::Application.routes.draw do
 
  resources :users

  resources :sites do
    collection do
      get :index_remote,:last_sync
      post :last_sync,:site_codes
    end
  end

  resources :npid_requests do
    collection do
      post :get_npids, :ack, :get_npids_in_batch, :acknowledge, :save_requested_ids
      get :get_npids, :ack, :get_npids_in_batch, :acknowledge, :save_requested_ids
    end
  end

  resources :npid_auto_generations do
    collection do
      post :master_available_npids, :create_npids
      get :master_available_npids, :create_npids
    end
  end

  resources :national_patient_identifiers do
    collection do
      get  'site/:site_id', :action => :for_site, :as => :site_specific
    end
  end

  resources :people do
    member do
      get :remote, :action => :show_remote 
    end

    collection do
      post :sync_demographics_with_master, :sync_demographics_with_proxy, 
           :sync_demographics_with_client,:find, :proxy_people_to_sync, 
           :demographics_to_sync, :master_people_to_sync, :record_successful_sync,
           :replace_national_id, :post_back_person, :record_sync_starttime, 
           :find_demographics, :create_footprint, :push_footprints,:create_for_sub_proxy,
           :push_demographics_to_traditional_authority,:acknowledge_traditional_authority_push,
           :footprints_to_push, :push_footprints_to_master, :record_successful_footprint_push,
           :update_demographics
           

      get :find, :sync_demographics_with_master, :sync_demographics_with_proxy, 
          :sync_demographics_with_client, :proxy_people_to_sync, :demographics_to_sync, 
          :master_people_to_sync, :record_successful_sync,:replace_national_id,
          :reassign_identication, :post_back_person, :record_sync_starttime, 
          :find_demographics, :create_footprint, :push_footprints,:create_for_sub_proxy,
          :push_demographics_to_traditional_authority,:acknowledge_traditional_authority_push,
          :footprints_to_push, :push_footprints_to_master, :record_successful_footprint_push,
          :update_demographics
    end
  end

  resource :login do
    collection do
      get :logout
    end
  end

  root :to => 'logins#show'
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  
  before_filter :load_person,
      :only => [:show, :edit, :update, :destroy, :conflict]

  # GET /people
  # GET /people.xml
  def index
    #@people = Person.page(params[:page]).all
    @people = Person.page(params[:page]).joins(:national_patient_identifier).select("people.*")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @people }
    end
  end

  # GET /people/1
  # GET /people/1.xml
  # GET /people/1.json
  def show
    if @person.nil?
      if Site.master?
        head :not_found
      else
        show_remote
      end
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml  => @person }
        format.json { render :json => @person.to_json }
      end
    end
  end

  def reassign_identication
    person = reassign_national_identification(params[:person_id])
    render :text => person.national_patient_identifier.value and return
  end

  def post_back_person
    person = reassign_national_identification(params[:person_id])
    render :text => person.to_json and return
  end
  
  #............................................................................
  def find_demographics

    given_name_code = params[:person][:names]["given_name"].soundex 
    family_name_code = params[:person][:names]["family_name"].soundex 
    gender = params[:person]["gender"]          
    
    if params[:person]['birth_year'] == "Unknown"                            
      birthdate = Date.new(Date.today.year - params[:person]["age_estimate"].to_i, 7, 1)
    else                                                                     
      year = params[:person]["birth_year"].to_i                              
      month = params[:person]["birth_month"]                           
      day = params[:person]["birth_day"].to_i                                
                                                                              
      month_i = (month || 0).to_i                                            
      month_i = Date::MONTHNAMES.index(month) if month_i == 0 || month_i.blank?
      month_i = Date::ABBR_MONTHNAMES.index(month) if month_i == 0 || month_i.blank?
                                                                              
      if month_i == 0 || month == "Unknown"                                  
        birthdate = Date.new(year.to_i,7,1)                                  
      elsif day.blank? || day == "Unknown" || day == 0                       
        birthdate = Date.new(year.to_i,month_i,15)                           
      else                                                                   
        birthdate = Date.new(year.to_i,month_i,day.to_i)                     
      end                                                                    
    end

    start_birthdate = (birthdate - 5.year)
    end_birthdate = (birthdate + 5.year)

    ta = params[:person][:addresses]['county_district']                   
    home_district = params[:person][:addresses]['address2']               
    home_village = params[:person][:addresses]['neighborhood_cell'] 

    ta = '"county_district":"' + ta 
    home_district = '"address2":"' + home_district
    home_village = '"neighborhood_cell":"' + home_village 


    @people = Person.joins("INNER JOIN national_patient_identifiers i 
      ON i.person_id = people.id AND i.voided = 0 INNER JOIN person_name_codes c 
      ON c.person_id = people.id").where("(given_name_code LIKE (?) 
      AND family_name_code LIKE (?)) AND people.gender = ? AND
      birthdate >='#{start_birthdate}' AND birthdate <='#{end_birthdate}' AND 
      (people.data LIKE (?) AND people.data LIKE (?) AND people.data LIKE (?))
      ","%#{given_name_code}","%#{family_name_code}%",gender,
      "%#{ta}%","%#{home_district}%","%#{home_village}%").select("people.*, i.value").group("people.id")
 
    case @people.size
    when 0
      if Site.master?
        head :not_found
      else
#       find_remote
        respond_to do |format|
          format.json do |f|
            render :text => {}.to_json
          end
        end
      end
    when 1
      respond_to do |format|
        format.html do |f|
          @person = @people.first
          render :action => 'show'
        end
        format.xml  { render :xml  => @people }
        format.json { render :json => @people.to_json }
      end
    else
      respond_to do |format|
        format.html { render :action => 'index',         :status => :multiple_choices }
        format.xml  { render :xml    => @people,         :status => :multiple_choices }
        format.json { render :json   => @people.to_json } #, :status => :multiple_choices }
      end
    end
  end
  #............................................................................


  # GET /people/find
  # GET /people/find.xml?given_name=:given_name&family_name=:family_name
  def find
    if not params[:value].blank?
      national_id = params[:value].gsub('-','')
      people = Person.joins(:national_patient_identifier).where('national_patient_identifiers.value' => national_id).select("people.*,national_patient_identifiers.value")
      
      @people = Person.joins([:national_patient_identifier,
        :legacy_national_ids]).where('legacy_national_ids.value' => national_id).select("people.*,national_patient_identifiers.value,legacy_national_ids.value AS old_identification_number")

      (people || []).each do |person|
        next if @people.collect{|p|p.id}.include?(person.id)
        @people << person
      end

      people = Person.joins(:legacy_national_ids).where('legacy_national_ids.value' => national_id).select("people.*,value AS old_identification_number")

      (people || []).each do |person|                                         
        next if @people.collect{|p|p.id}.include?(person.id)                  
        @people << person                                                     
      end 
    else
      @people = Person.search(params)
    end
    
    case @people.size
    when 0
      if Site.master?
        head :not_found
      else
#       find_remote
        respond_to do |format|
          format.json do |f|
            render :text => {}.to_json
          end
        end
      end
    when 1
      respond_to do |format|
        format.html do |f|
          @person = @people.first
          render :action => 'show'
        end
        format.xml  { render :xml  => @people }
        format.json { render :json => @people.to_json }
      end
    else
      respond_to do |format|
        format.html { render :action => 'index',         :status => :multiple_choices }
        format.xml  { render :xml    => @people,         :status => :multiple_choices }
        format.json { render :json   => @people.to_json } #, :status => :multiple_choices }
      end
    end
  end

  # GET /people/new
  # GET /people/new.xml
  def new
    @person = Person.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.xml
  def create
    passed_national_id = (params[:person]['data']['patient']['identifiers']['old_identification_number'])

    unless passed_national_id.blank?
      national_id = passed_national_id.gsub('-','').strip

      @person = Person.where("legacy_national_ids.value = ?",national_id).includes([:legacy_national_ids]).first rescue nil

      if @person.blank?
        @person = Person.where("national_patient_identifiers.value = ?",national_id).includes([:national_patient_identifier]).first rescue nil
      end

      if @person
        respond_to do |format|
            format.html { redirect_to(@person, :notice => 'Person was successfully created.') }
            format.xml  { render :xml  => @person, :status => :created, :location => @person }
            format.json { render :json => @person, :status => :created, :location => @person }
        end
      end
      return if not @person.blank?
    end

    version = Guid.new.to_s
    @person = Person.new(params[:person].merge(
                         {:creator_site_id => Site.current_id ,
                         :given_name => params[:person]["data"]["names"]["given_name"] ,
                         :family_name => params[:person]["data"]["names"]["family_name"] ,
                         :gender => params[:person]["data"]["gender"] ,
                         :birthdate => params[:person]["data"]["birthdate"] ,
                         :birthdate_estimated => params[:person]["data"]["birthdate_estimated"],
                         :version_number => version,
                         :remote_version_number => version }
                        ))

    respond_to do |format|
      if @person.save
        if not passed_national_id.blank?
          legacy_national_id = LegacyNationalIds.new()
          legacy_national_id.person_id = @person.id
          legacy_national_id.value = national_id
          legacy_national_id.save
        end
        format.html { redirect_to(@person, :notice => 'Person was successfully created.') }
        format.xml  { render :xml  => @person, :status => :created, :location => @person }
        format.json { render :json => @person, :status => :created, :location => @person }
      else
        status = @person.errors.delete(:status) || :unprocessable_entity

        format.html { render :action => 'new' }
        format.xml  { render :xml  => @person.errors, :status => status }
        format.json { render :json => @person.errors, :status => status }
      end
    end
  end

  def create_for_sub_proxy

    JSON.parse(params['demographics']).each do |key, demographic|

      version = Guid.new.to_s
      person_hash = {'person' => {"family_name" => demographic['person']['family_name'],
                                  "given_name" => demographic['person']['given_name'],

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_conflict_form.html.erb
<%= form_for(person) do |f| %>
  <%= f.hidden_field :remote_version_number %>
  <%= f.hidden_field :version_number %>

  <div class="field">
    <%= f.label :npid_value %><br />
    <%= f.text_field :npid_value %>
  </div>

  <div class="field">
    <%= f.label :creator_site_id %><br />
    <%= f.collection_select :creator_site_id, Site.all, :id, :name, :include_blank => true %>
  </div>

  <div class="field">
    <%= f.label :data_as_yaml, 'Data' %><br />
    <%= f.text_area :data_as_yaml %>
  </div>

  <div class="actions">
    <%= f.submit 'Keep this Version' %>
  </div>
<% end %>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, 'error') %> prohibited this person from being saved:</h2>

      <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :version_number %>

  <div class="field">
    <%= f.label :npid_value %><br />
    <%= f.text_field :npid_value %>
  </div>

  <div class="field">
    <%= f.label :creator_site_id %><br />
    <%= f.collection_select :creator_site_id, Site.all, :id, :name, :include_blank => true %>
  </div>

  <div class="field">
    <%= f.label :data_as_yaml, 'Data' %><br />
    <%= f.text_area :data_as_yaml, :size => '100x10' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/conflict.html.erb
<h2>Oops!</h2>

<p>You ran into a conflict while trying to update this person record. Please
compare your and the remote version below, edit as necessary and submit the
version you want to keep.</p>

<div id="side-by-side-container">
  <div id="left-container">
    <h3>Your (new) Version</h3>
    <%= render 'conflict_form', :person => @local_person %>
  </div>

  <div id="right-container">
    <h3>Remote (existing) Version</h3>
    <%= render 'conflict_form', :person => @remote_person %>
  </div>
</div>

<hr />

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %> |
<%= link_to 'Pull from Master', remote_person_path(@person) if can? :show_remote, @person %>

app/views/people/edit.html.erb
<h2>Editing person</h2>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %> |
<%= link_to 'Pull from Master', remote_person_path(@person) if can? :show_remote, @person %>

app/views/people/index.html.erb
<script>
  
  var PatientsIDs = "";
  var PatientsIDsBatch = {};
  var ids = []
  var count = 0;

  var PatientIDsFromMaster = {};

  function getListOfPatientIDs() {
    PatientsIDsBatch = {};
    count = 1;
    PatientsIDsBatch[count] = [];
    PatientsIDs = PatientsIDs.sort(function(a,b){return a - b});

    for(var i = 0; i < PatientsIDs.length; i++) {
      if (PatientsIDsBatch[count].length < 11) {
        ids.push(PatientsIDs[i]);
        PatientsIDsBatch[count] = ids;
      }else{
        count++;
        ids = [];
        ids.push(PatientsIDs[i]);
        PatientsIDsBatch[count] = ids;
      }
    }
    syncWithMaster();
  }
 
 function availableIDS() {
    if (window.XMLHttpRequest) {// code for IE7+, Firefox, Chrome, Opera, Safari 
      xmlhttp=new XMLHttpRequest();                                              
    }else{// code for IE6, IE5                                                   
      xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");                            
    }                                                                            
                                                                                
    xmlhttp.onreadystatechange=function() {                                      
      if (xmlhttp.readyState==4 && xmlhttp.status==200) {                        
        var results = eval(xmlhttp.responseText);                                      
        if(results) {
           PatientsIDs = results;
           getListOfPatientIDs();
        }
      }                                                                          
    }                                                                            
                                                                                
    xmlhttp.open("GET","/people/people_to_sync" , true);              
      
    xmlhttp.send();

 } 

  function syncWithMaster() {
    for(key in PatientsIDsBatch) {
      sendDemographicsFile(key , PatientsIDsBatch[key].join(','));
    }
    availableMasterIDS();
  }



 function syncWithProxy(){
     for(key in PatientIDsFromMaster) {
      getDemographicsFile(key , PatientIDsFromMaster[key].join(','));
    }
 }
 

  function sendDemographicsFile(key , patient_ids) {
    if(patient_ids.length < 1)
      return;


    if (window.XMLHttpRequest) {// code for IE7+, Firefox, Chrome, Opera, Safari 
      xmlhttp=new XMLHttpRequest();                                              
    }else{// code for IE6, IE5                                                   
      xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");                            
    }                                                                            
                                                                                
    xmlhttp.onreadystatechange=function() {                                      
      if (xmlhttp.readyState==4 && xmlhttp.status==200) {                        
        var results = xmlhttp.responseText;                                      
        if(results == "updated master") {
          delete PatientsIDsBatch[key];
          syncWithMaster();
        }
      }                                                                          
    }                                                                            
                                                                                
    var params = "patient_ids=" + patient_ids;
    xmlhttp.open("GET","/people/sync_demographics_with_master?" + params , true);              
    xmlhttp.send();

  }


  function availableMasterIDS() {
    if (window.XMLHttpRequest) {// code for IE7+, Firefox, Chrome, Opera, Safari
      xmlhttp=new XMLHttpRequest();
    }else{// code for IE6, IE5
      xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
    }

  xmlhttp.onreadystatechange=function() {
      if (xmlhttp.readyState==4 && xmlhttp.status==200) {
        var results = eval(xmlhttp.responseText);
        if(results) {
          a = JSON.parse(results);
          a.sort(function(x,y){return x - y})
          ids2 = [];
          count = 1;
          PatientIDsFromMaster[count] = [];
          for(var i = 0; i < a.length; i++) {
            if (PatientIDsFromMaster[count].length < 11) {
              ids2.push(a[i]);
              PatientIDsFromMaster[count] = ids2;
            }else{
              count++;
              ids2 = [];
              ids2.push(a[i]);
              PatientIDsFromMaster[count] = ids2;
            }
          }
          if(PatientIDsFromMaster[1].length > 0)
            syncWithProxy();
           
        }
      }
    }        

  xmlhttp.open("GET","/people/getPeopleIdsCount" , true);

  xmlhttp.send();

 }

  function getDemographicsFile(key , patient_ids) {
    if (window.XMLHttpRequest) {// code for IE7+, Firefox, Chrome, Opera, Safari
      xmlhttp=new XMLHttpRequest();
    }else{// code for IE6, IE5
      xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
    }

    xmlhttp.onreadystatechange=function() {
      if (xmlhttp.readyState==4 && xmlhttp.status==200) {
        var results = xmlhttp.responseText;
        if(results == "updated proxy") {
          delete PatientIDsFromMaster[key];
          syncWithProxy();
        }
      }
    }

    var params = "patient_ids=" + patient_ids;
    xmlhttp.open("GET","/people/sync_demographics_with_proxy?" + params , true);
    xmlhttp.send();

  }

</script>


<h2>Listing people</h2>

<table class="table">
  <tr>
    <th>NPID</th>
    <th>Created at</th>
    <th>Last updated by</th>
    <th>Last updated at site</th>
    <th>Version</th>
    <th style="width: 130px;"></th>
  </tr>

  <% @people.each do |person| %>
  <%#=raise person.to_yaml%>
    <tr>
      <td><%= link_to person.npid_value, person %></td>
      <td><%= person.created_at %></td>
      <td><%= person.creator_id || ' - unknown - ' %></td>
      <td><%= Site.find_by_id(person.creator_site_id).name rescue ' - unknown - ' %></td>
      <td><%= person.version_number.last(12) rescue 0 %></td>
      <td>
        <%= link_to 'Show', person if can? :show, person %> |
        <%= link_to 'Edit', edit_person_path(person) if can? :edit, person %> |
        <%#= link_to 'Sync', remote_person_path(person) if can? :show_remote, person %>
      </td>
    </tr>
  <% end %>
</table>

<%= will_paginate @people %>
<br />
<p>
  <div id="new" align="center">
    <%= link_to 'New Person', new_person_path %>
  </div>
</p>

<br />                                                                          

<%if Site.proxy? %>
  <%#= link_to 'Sync With Master', "javascript:availableIDS();" %>
<%end%>

app/views/people/new.html.erb
<h2>New person</h2>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<h2>Person details</h2>

<p>
  <b>Record Version:</b>
  <%= @person.version_number  %>
</p>

<p>
  <b>National Patient ID:</b>
  <%= link_to @person.npid_value, @person.npid %>
</p>

<p>
  <b>Creator Site:</b>
  <%= link_to @person.creator_site.try(:name), @person.creator_site %>
</p>

<p>
  <b>Data:</b>
  <pre><%= @person.data.to_yaml %></pre>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>