config/routes.rb
DdeServer::Application.routes.draw do
 
  resources :users

  resources :sites do
    collection do
      get :index_remote,:last_sync
      post :last_sync,:site_codes
    end
  end

  resources :npid_requests do
    collection do
      post :get_npids, :ack, :get_npids_in_batch, :acknowledge, :save_requested_ids
      get :get_npids, :ack, :get_npids_in_batch, :acknowledge, :save_requested_ids
    end
  end

  resources :npid_auto_generations do
    collection do
      post :master_available_npids, :create_npids
      get :master_available_npids, :create_npids
    end
  end

  resources :national_patient_identifiers do
    collection do
      get  'site/:site_id', :action => :for_site, :as => :site_specific
    end
  end

  resources :people do
    member do
      get :remote, :action => :show_remote 
    end

    collection do
      post :sync_demographics_with_master, :sync_demographics_with_proxy, 
           :sync_demographics_with_client,:find, :proxy_people_to_sync, 
           :demographics_to_sync, :master_people_to_sync, :record_successful_sync,
           :replace_national_id, :post_back_person, :record_sync_starttime, 
           :find_demographics, :create_footprint, :push_footprints,:create_for_sub_proxy,
           :push_demographics_to_traditional_authority,:acknowledge_traditional_authority_push,
           :footprints_to_push, :push_footprints_to_master, :record_successful_footprint_push,
           :update_demographics
           

      get :find, :sync_demographics_with_master, :sync_demographics_with_proxy, 
          :sync_demographics_with_client, :proxy_people_to_sync, :demographics_to_sync, 
          :master_people_to_sync, :record_successful_sync,:replace_national_id,
          :reassign_identication, :post_back_person, :record_sync_starttime, 
          :find_demographics, :create_footprint, :push_footprints,:create_for_sub_proxy,
          :push_demographics_to_traditional_authority,:acknowledge_traditional_authority_push,
          :footprints_to_push, :push_footprints_to_master, :record_successful_footprint_push,
          :update_demographics
    end
  end

  resource :login do
    collection do
      get :logout
    end
  end

  root :to => 'logins#show'
end

app/models/site.rb
# == Schema Information
#
# Table name: sites
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  annotations :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  code        :string(255)      default("")
#

class Site < ActiveRecord::Base

  has_many :users

  has_many :npid_auto_generations

  has_many :national_patient_identifiers,
      :foreign_key => :assigner_site_id



  def available_npids
    if SITE_CONFIG[:mode] == 'master'
      self.national_patient_identifiers.where(:pulled => nil)
    else
      self.national_patient_identifiers.where(:assigned_at => nil)
    end
  end

  def assigned_npids
    if SITE_CONFIG[:mode] == 'master'
      self.national_patient_identifiers.where(:pulled => true)
    else
      self.national_patient_identifiers.where('assigned_at IS NOT NULL')
    end
  end
  
  def self.current_id
    SITE_CONFIG[:site_id].to_i
  end

  def self.current     
    if self.proxy?
      self.find self.current_id
    end
  end

  def self.current_name
    if self.proxy?
      self.current.try(:name) || '- unknown -'
    else
      'Master Service'
    end
  end

  def self.current_code
    if self.proxy?
      self.current.try(:code) || '???'
    else
      'DDE'
    end
  end

  def self.master?
    SITE_CONFIG[:mode] == 'master'
  end

  def self.proxy?
    SITE_CONFIG[:mode] == 'proxy'
  end

  def self.sync_with_master!
    if Site.proxy?
      response = self.base_resource.get(:accept => :json)
      ActiveSupport::JSON.decode(response).each do |data_set|
        self.find_or_create_from_attributes(data_set['site'], :update => true)
      end
    end
    
    "OK"
  rescue => e
    Rails.logger.error "#{e} while trying to fetch site information from master"
  end

  def self.find_or_create_from_attributes(attrs, options = {:update => false})
    if attrs['id']
      self.find_or_initialize_by_id(attrs.delete('id')).tap do |site|
        site.update_attributes(attrs) if site.new_record? or options[:update]
      end
    else
      raise ArgumentError, %q(expected attrs hash to have key named 'id')
    end
  end

  def remote_attributes
    { 'site' => self.attributes }
  end

  def to_json(includes = {})
    self.remote_attributes.merge(includes).to_json
  end

  protected

  def self.base_resource
    @base_resource ||= RestClient::Resource.new(SITE_CONFIG[:master_uri], SITE_CONFIG[:remote_http_options].to_hash.symbolize_keys)['sites']
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  
  # GET /sites
  # GET /sites.xml
  def index
    @sites = Site.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @sites }
      format.xml  { render :xml  => @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.xml
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @site }
      format.xml  { render :xml  => @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.xml
  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @site }
      format.xml  { render :xml  => @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
  end

  # POST /sites
  # POST /sites.xml
  def create
    @site = Site.new(params[:site])

    respond_to do |format|
      if @site.save
        format.html { redirect_to(@site, :notice => 'Site was successfully created.') }
        format.json { render :json => @site, :status => :created, :location => @site }
        format.xml  { render :xml  => @site, :status => :created, :location => @site }
      else
        format.html { render :action => "new" }
        format.json { render :json => @site.errors, :status => :unprocessable_entity }
        format.xml  { render :xml  => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.xml
  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to(@site, :notice => 'Site was successfully updated.') }
        format.json { head :ok }
        format.xml  { head :ok }
      else
        format.html { render :action => '#edit' }
        format.json { render :json => @site.errors, :status => :unprocessable_entity }
        format.xml  { render :xml  => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.xml
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to(sites_url) }
      format.json { head :ok }
      format.xml  { head :ok }
    end
  end

  def index_remote
    resp = Site.sync_with_master!
    @sites  = Site.all

    if resp == "OK" 
      flash[:notice] = 'Sync with master completed successfully!'
    else 
      flash[:error] = resp
    end

    respond_to do |format|
      format.html { render :action => 'index' }
      format.json { render :json => @sites }
      format.xml  { render :xml => @sites }
    end
  end

  def perform_basic_auth
    if %w(index show index_remote).include? params[:action]
      super
    else
      authorize! :manage, Site
    end
  end

  def last_sync
  
    if Site.master? and params[:site_code]
      site_code = params[:site_code]
      site_name = Site.find_by_code(site_code).name rescue nil
      return "Unknown Site".to_json if site_name.blank?
      complete_sync = nil
      last_incomplete_sync = MasterSyncs.where("site_code = '#{site_code}'
                                    AND created_date IS NOT NULL
                                    AND updated_date IS NULL").
                              order("created_date DESC").
                              select("created_date").
                              limit(1)

      unless last_incomplete_sync.blank?
           complete_sync = false
           render :text => [site_name,complete_sync,last_incomplete_sync.first.created_date].to_json and return
      else
           last_sync = MasterSyncs.where("site_code = '#{site_code}'
                                          AND created_date IS NOT NULL
                                          AND updated_date IS NOT NULL").
                                          order("updated_date DESC").
                                          select("updated_at").
                                          limit(1)
           unless last_sync.blank?
             complete_sync = true
             render :text => [site_name,complete_sync,last_sync.first.updated_at.strftime('%Y-%b-%d %H:%M:%S')].to_json and return
           else
             render :text => [site_name,complete_sync].to_json and return
           end
      end  
    end
  end

  def site_codes
    site_codes = Site.all.collect {|site| site.code}
    render :text => site_codes.to_json and return
  end

end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, 'error') %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>

  <div class="field">
    <%= f.label :annotations %><br />
    <%= f.text_field :annotations %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h2>Editing site</h2>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<h2>Listing sites</h2>

<table class="table">
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Code</th>
    <th>Annotations</th>
    <th>Available NPIDS</th>
    <% if Site.master? %>
      <th>Assigned NPIDS</th>
    <% end %>
    <th style="width: 130px;"></th>
  </tr>

  <% @sites.each do |site| %>
    <tr>
      <td><%= site.id %></td>
      <td><%= link_to site.name, site %></td>
      <td><%= site.code %></td>
      <td><%= site.annotations %></td>
      <% if Site.master? %>
      <td><%= site.available_npids.count %></td>
      <td><%= site.assigned_npids.count %></td>
      <% else %>
        <td><%= site.available_npids.count %></td>
      <% end %>
      <td>
        <%= link_to 'Show', site %> |
        <%= link_to 'Edit', edit_site_path(site) if can? :edit, site %> |
        <%= link_to 'Destroy', site, :confirm => 'Are you sure?', :method => :delete if can? :destroy, site %>
      </td>
    </tr>
  <% end %>
</table>

<br />

<%if Site.master?%> 
  <%= link_to 'New Site', new_site_path if can? :create, Site %>
<%else%>
<%= link_to 'Synchronize with Master', index_remote_sites_path %>
<%end%>

app/views/sites/new.html.erb
<h2>New site</h2>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p>
  <b>Name:</b>
  <%= @site.name %>
</p>

<p>
  <b>Code:</b>
  <%= @site.code %>
</p>

<p>
  <b>Annotations:</b>
  <%= @site.annotations %>
</p>


<%= link_to 'Edit', edit_site_path(@site) if can? :edit, @site %> |
<%= link_to 'Back', sites_path %>