config/routes.rb
DdeServer::Application.routes.draw do
 
  resources :users

  resources :sites do
    collection do
      get :index_remote,:last_sync
      post :last_sync,:site_codes
    end
  end

  resources :npid_requests do
    collection do
      post :get_npids, :ack, :get_npids_in_batch, :acknowledge, :save_requested_ids
      get :get_npids, :ack, :get_npids_in_batch, :acknowledge, :save_requested_ids
    end
  end

  resources :npid_auto_generations do
    collection do
      post :master_available_npids, :create_npids
      get :master_available_npids, :create_npids
    end
  end

  resources :national_patient_identifiers do
    collection do
      get  'site/:site_id', :action => :for_site, :as => :site_specific
    end
  end

  resources :people do
    member do
      get :remote, :action => :show_remote 
    end

    collection do
      post :sync_demographics_with_master, :sync_demographics_with_proxy, 
           :sync_demographics_with_client,:find, :proxy_people_to_sync, 
           :demographics_to_sync, :master_people_to_sync, :record_successful_sync,
           :replace_national_id, :post_back_person, :record_sync_starttime, 
           :find_demographics, :create_footprint, :push_footprints,:create_for_sub_proxy,
           :push_demographics_to_traditional_authority,:acknowledge_traditional_authority_push,
           :footprints_to_push, :push_footprints_to_master, :record_successful_footprint_push,
           :update_demographics
           

      get :find, :sync_demographics_with_master, :sync_demographics_with_proxy, 
          :sync_demographics_with_client, :proxy_people_to_sync, :demographics_to_sync, 
          :master_people_to_sync, :record_successful_sync,:replace_national_id,
          :reassign_identication, :post_back_person, :record_sync_starttime, 
          :find_demographics, :create_footprint, :push_footprints,:create_for_sub_proxy,
          :push_demographics_to_traditional_authority,:acknowledge_traditional_authority_push,
          :footprints_to_push, :push_footprints_to_master, :record_successful_footprint_push,
          :update_demographics
    end
  end

  resource :login do
    collection do
      get :logout
    end
  end

  root :to => 'logins#show'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Baobab DDE@<%= Site.current_name %></title>
  <%= stylesheet_link_tag 'web-app-theme/base', 'web-app-theme/themes/drastic-dark/style', 'web-app-theme/override', 'dde', :cache => true %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">Baobab DDE<sub style="font-size:0.8em; color: gray;"><%= app_version %></sub>@<%= Site.current_name %></a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <% if can? :acces, :login %>
            <li><a href="/login/logout" class="logout">Logout</a></li>
          <% else %>
            <li>
              <%= link_to 'Logout', logout_login_path %>
            </li>
          <% end %>
        </ul>
      </div>
      <div id="main-navigation">
        <% if can? :access, :anything %>
          <ul class="wat-cf">
            <li class="<%= params[:controller] == 'people' ? 'active' : '' %>">
              <%= link_to 'Patient Management', people_path %>
            </li>
            <li class="<%= params[:controller] == 'users' ? 'active' : '' %>">
              <%= link_to 'User Management', users_path %>
            </li>
            <li class="<%= params[:controller] == 'national_patient_identifiers' ? 'active' : '' %>">
              <%= link_to 'NPID Management', national_patient_identifiers_path %>
            </li>
            <li class="<%= params[:controller] == 'npid_auto_generations' ? 'active' : '' %>">
              <%= link_to Site.proxy?? 'NPID Auto Request' : 'NPID Auto Generation', npid_auto_generations_path %>
            </li>
            <li class="<%= params[:controller] == 'sites' ? 'active' : '' %>">
              <%= link_to 'Site Management', sites_path %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>    

    <div id="wrapper" class="wat-cf">
      <%= flash_messages %>
      <div id="main">
        <div class="block">
          <div class="content">
            <div class="inner">
              <%= yield %>
            </div>
          </div>
        </div>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> <a href="http://www.baobabhealth.org" target="_blank">Baobab Health</a>.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Baobab DDE@<%= Site.current_name %></title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/drastic-dark/style", "web-app-theme/override", :cache => true %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">Baobab DDE<sub style="font-size:0.8em; color: gray;"><%= app_version %></sub>@<%= Site.current_name %></a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <% if can? :acces, :login %>
            <li><a href="/login/logout" class="logout">Logout</a></li>
          <% end %>
        </ul>
      </div>
      <div id="main-navigation"></div>
    </div>    

    <div id="wrapper" class="wat-cf">
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> <a href="http//baobabhealth.org">Baobab Health</a>.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>